In [1]:
import pandas, numpy
from pathlib import Path
from datetime import datetime
import json

CWD = Path("C:\\Users\\정진혁\\offline_main\\projectXpython")
SOURCE = CWD / 'source'
RESULT_STORAGE = CWD / 'result_storage'
MASSIVE_RESULT_STORAGE = Path('../MassiveResultStorage')

DATAS = Path("../datas")
ARTICLE_JSONS = DATAS / 'article_jsons'
TWITTER_JSONS = DATAS / 'twitter_jsons'

def print_log(message:str):
    print(f"{datetime.now()}\t{message}")

def import_file(file_path:Path):

    if file_path.suffix == ".xlsx":
        df = pandas.read_excel(file_path)
    elif file_path.suffix == ".csv":
        df = pandas.read_csv(file_path)
    else:
        print_log(f"skipped: {file_path} is not xlsx or csv file.")
    
    print_log(f"imported: {file_path}")

    return df

source_path = SOURCE / "catch_duplication"
result_path = RESULT_STORAGE / "catch_duplication"
reference_file = RESULT_STORAGE / "temp/catch_duplicate.json"

In [2]:
"""
1. xlsx 파일, csv 파일을 각각 확장자별로 분리해 xl_df, csv_df에 저장한다.
2. reference_file은 catch_duplicate.json 파일이며, 이 파일에는 중복되는 Doc_ID의 리스트가 저장되어 있다.
3. xl_df에 csv_df의 데이터를 추가하되, reference_file에 저장된 Doc_ID에 대해서는 xl_df에 추가하지 않는다.
4. xl_df를 저장하되, xl_df의 행이 5만 개가 넘어가면, 5만 개씩 잘라서 result_path에 저장하고, 파일명을 "20231204_원천데이터(기사+한국관련기사)_중복제거_{i}.xlsx"로 저장한다.
"""
xl_df = pandas.DataFrame()
csv_df = pandas.DataFrame()
ref:list = json.load(reference_file.open(encoding="utf-8"))

xl_df_list = []
csv_df_list = []

for file_path in source_path.glob("**/*.*"):
    df = import_file(file_path)

    if file_path.suffix == ".xlsx": xl_df_list.append(df)
    elif file_path.suffix == ".csv": csv_df_list.append(df)
    else: continue

xl_df = pandas.concat(xl_df_list)
csv_df = pandas.concat(csv_df_list)

xl_df, csv_df

C:\Users\정진혁\AppData\Local\Temp\ipykernel_21024\3894429526.py:23: DtypeWarning: Columns (86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pandas.read_csv(file_path)

2023-12-04 14:22:54.469081	imported: C:\Users\정진혁\offline_main\projectXpython\source\catch_duplication\비교군\202300906_원천데이터(기사)_1.csv

C:\Users\정진혁\AppData\Local\Temp\ipykernel_21024\3894429526.py:23: DtypeWarning: Columns (103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pandas.read_csv(file_path)

2023-12-04 14:22:58.793865	imported: C:\Users\정진혁\offline_main\projectXpython\source\catch_duplication\비교군\202300906_원천데이터(기사)_2.csv

C:\Users\정진혁\AppData\Local\Temp\ipykernel_21024\3894429526.py:23: DtypeWarning: Columns (91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pandas.read_csv(file_path)

2023-12-04 14:23:01.371241	imported: C:\Users\정진혁\offline_main\projectXpython\source\catch_duplication\비교군\202300906_원천데이터(기사)_3.csv

C:\Users\정진혁\AppData\Local\Temp\ipykernel_21024\3894429526.py:23: DtypeWarning: Columns (86,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pandas.read_csv(file_path)

2023-12-04 14:23:04.043888	imported: C:\Users\정진혁\offline_main\projectXpython\source\catch_duplication\비교군\202300906_원천데이터(기사)_4.csv

C:\Users\정진혁\AppData\Local\Temp\ipykernel_21024\3894429526.py:23: DtypeWarning: Columns (89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pandas.read_csv(file_path)

2023-12-04 14:23:06.786208	imported: C:\Users\정진혁\offline_main\projectXpython\source\catch_duplication\비교군\202300906_원천데이터(기사)_5.csv

C:\Users\정진혁\AppData\Local\Temp\ipykernel_21024\3894429526.py:23: DtypeWarning: Columns (85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pandas.read_csv(file_path)

2023-12-04 14:23:10.045316	imported: C:\Users\정진혁\offline_main\projectXpython\source\catch_duplication\비교군\202300906_원천데이터(기사)_6.csv

C:\Users\정진혁\AppData\Local\Temp\ipykernel_21024\3894429526.py:23: DtypeWarning: Columns (79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pandas.read_csv(file_path)

2023-12-04 14:23:14.540986	imported: C:\Users\정진혁\offline_main\projectXpython\source\catch_duplication\비교군\202300906_원천데이터(기사)_7.csv

C:\Users\정진혁\AppData\Local\Temp\ipykernel_21024\3894429526.py:23: DtypeWarning: Columns (85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pandas.read_csv(file_path)

2023-12-04 14:23:16.611710	imported: C:\Users\정진혁\offline_main\projectXpython\source\catch_duplication\비교군\202300906_원천데이터(기사)_8.csv
2023-12-04 14:28:40.820817	imported: C:\Users\정진혁\offline_main\projectXpython\source\catch_duplication\원본\20231004_원천데이터(기사)_3_정제완료.xlsx
2023-12-04 14:34:19.008206	imported: C:\Users\정진혁\offline_main\projectXpython\source\catch_duplication\원본\20231004_원천데이터(기사)_4_정제완료.xlsx
2023-12-04 14:39:40.163822	imported: C:\Users\정진혁\offline_main\projectXpython\source\catch_duplication\원본\20231004_원천데이터(기사)_5_정제완료.xlsx
2023-12-04 14:41:55.278596	imported: C:\Users\정진혁\offline_main\projectXpython\source\catch_duplication\원본\20231004_원천데이터(기사)_7_정제완료.xlsx
2023-12-04 14:42:01.345213	imported: C:\Users\정진혁\offline_main\projectXpython\source\catch_duplication\원본\20231005_원천데이터(기사)_10.xlsx
2023-12-04 14:43:04.527615	imported: C:\Users\정진혁\offline_main\projectXpython\source\catch_duplication\원본\20231005_원천데이터(기사)_8.5.xlsx
2023-12-04 14:43:38.132736	imported: C:\Users\정진혁\offline_main\projectXpython\source\catch_duplication\원본\20231005_원천데이터(기사)_8.xlsx
2023-12-04 14:45:46.726057	imported: C:\Users\정진혁\offline_main\projectXpython\source\catch_duplication\원본\20231005_원천데이터(기사)_9.xlsx
2023-12-04 14:48:24.921414	imported: C:\Users\정진혁\offline_main\projectXpython\source\catch_duplication\원본\20231024_원천데이터(한국관련기사)_11.xlsx
2023-12-04 14:49:59.609276	imported: C:\Users\정진혁\offline_main\projectXpython\source\catch_duplication\원본\20231024_원천데이터(한국관련기사)_12.xlsx
2023-12-04 14:52:00.655286	imported: C:\Users\정진혁\offline_main\projectXpython\source\catch_duplication\원본\20231024_원천데이터(한국관련기사)_13.xlsx
2023-12-04 14:53:34.393604	imported: C:\Users\정진혁\offline_main\projectXpython\source\catch_duplication\원본\20231024_원천데이터(한국관련기사)_14.xlsx

(                                   Doc_ID  \
 0          20230809_newsdata_Korea_001327
 1          20230809_newsdata_Korea_001327
 2          20230809_newsdata_Korea_001327
 3          20230809_newsdata_Korea_001327
 4          20230809_newsdata_Korea_001327
 ...                                   ...
 44177  20231023_newsdata_Yoo Ah in_000249
 44178  20231023_newsdata_Yoo Ah in_000249
 44179  20231023_newsdata_Yoo Ah in_000249
 44180  20231023_newsdata_Yoo Ah in_000249
 44181  20231023_newsdata_Yoo Ah in_000249

                                                 Filename  \
 0      C:/Users/USER/Desktop/news data/20230809_data/...
 1      C:/Users/USER/Desktop/news data/20230809_data/...
 2      C:/Users/USER/Desktop/news data/20230809_data/...
 3      C:/Users/USER/Desktop/news data/20230809_data/...
 4      C:/Users/USER/Desktop/news data/20230809_data/...
 ...                                                  ...
 44177  C:/Users/USER/Desktop/기사 데이터_로컬환경/20231023_dat...
 44178  C:/Users/USER/Desktop/기사 데이터_로컬환경/20231023_dat...
 44179  C:/Users/USER/Desktop/기사 데이터_로컬환경/20231023_dat...
 44180  C:/Users/USER/Desktop/기사 데이터_로컬환경/20231023_dat...
 44181  C:/Users/USER/Desktop/기사 데이터_로컬환경/20231023_dat...

                                                    Title   Pub_Type Pub_Subj  \
 0      SNSD Siap Comeback di Bulan Januari dengan Kon...  Newspaper    Korea
 1      SNSD Siap Comeback di Bulan Januari dengan Kon...  Newspaper    Korea
 2      SNSD Siap Comeback di Bulan Januari dengan Kon...  Newspaper    Korea
 3      SNSD Siap Comeback di Bulan Januari dengan Kon...  Newspaper    Korea
 4      SNSD Siap Comeback di Bulan Januari dengan Kon...  Newspaper    Korea
 ...                                                  ...        ...      ...
 44177  Park Ju Hyun Cerita Soal Film Barunya Bareng Y...  Newspaper      NaN
 44178  Park Ju Hyun Cerita Soal Film Barunya Bareng Y...  Newspaper      NaN
 44179  Park Ju Hyun Cerita Soal Film Barunya Bareng Y...  Newspaper      NaN
 44180  Park Ju Hyun Cerita Soal Film Barunya Bareng Y...  Newspaper      NaN
 44181  Park Ju Hyun Cerita Soal Film Barunya Bareng Y...  Newspaper      NaN

         Pub_Date   Col_Date                                        Sen_ID  \
 0     2013-12-07 2023-08-09      20230809_newsdata_Korea_001327_sen000004
 1     2013-12-07 2023-08-09      20230809_newsdata_Korea_001327_sen000005
 2     2013-12-07 2023-08-09      20230809_newsdata_Korea_001327_sen000006
 3     2013-12-07 2023-08-09      20230809_newsdata_Korea_001327_sen000007
 4     2013-12-07 2023-08-09      20230809_newsdata_Korea_001327_sen000008
 ...          ...        ...                                           ...
 44177 2021-11-08 2023-10-23  20231023_newsdata_Yoo Ah in_000249_sen000006
 44178 2021-11-08 2023-10-23  20231023_newsdata_Yoo Ah in_000249_sen000007
 44179 2021-11-08 2023-10-23  20231023_newsdata_Yoo Ah in_000249_sen000008
 44180 2021-11-08 2023-10-23  20231023_newsdata_Yoo Ah in_000249_sen000009
 44181 2021-11-08 2023-10-23  20231023_newsdata_Yoo Ah in_000249_sen000010

        Word_Count                                               Text  ...  \
 0              17  Girls' Generation akan comeback awal tahun dep...  ...
 1              15  Girls' Generation akan comeback awal tahun dep...  ...
 2              11  Girls' Generation akan comeback awal tahun dep...  ...
 3              14  Girls' Generation akan comeback awal tahun dep...  ...
 4               9  Girls' Generation akan comeback awal tahun dep...  ...
 ...           ...                                                ...  ...
 44177          22     Dalam wawancara dan pemotretan baru-baru in...  ...
 44178          28     Dalam wawancara dan pemotretan baru-baru in...  ...
 44179          17     Dalam wawancara dan pemotretan baru-baru in...  ...
 44180          29     Dalam wawancara dan pemotretan baru-baru in...  ...
 44181          15     Dalam wawancara dan pemotretan baru-baru in...  ...

       Column_519 Column_520 Column_521 Column_522 Column_523 Column_524  \
 0            NaN        NaN        NaN        NaN        NaN        NaN
 1            NaN        NaN        NaN        NaN        NaN        NaN
 2            NaN        NaN        NaN        NaN        NaN        NaN
 3            NaN        NaN        NaN        NaN        NaN        NaN
 4            NaN        NaN        NaN        NaN        NaN        NaN
 ...          ...        ...        ...        ...        ...        ...
 44177        NaN        NaN        NaN        NaN        NaN        NaN
 44178        NaN        NaN        NaN        NaN        NaN        NaN
 44179        NaN        NaN        NaN        NaN        NaN        NaN
 44180        NaN        NaN        NaN        NaN        NaN        NaN
 44181        NaN        NaN        NaN        NaN        NaN        NaN

       Column_525 Column_526 Column_527 Column_528
 0            NaN        NaN        NaN        NaN
 1            NaN        NaN        NaN        NaN
 2            NaN        NaN        NaN        NaN
 3            NaN        NaN        NaN        NaN
 4            NaN        NaN        NaN        NaN
 ...          ...        ...        ...        ...
 44177        NaN        NaN        NaN        NaN
 44178        NaN        NaN        NaN        NaN
 44179        NaN        NaN        NaN        NaN
 44180        NaN        NaN        NaN        NaN
 44181        NaN        NaN        NaN        NaN

 [455290 rows x 542 columns],
                                Doc_ID  \
 0      20230808_newsdata_Korea_000001
 1      20230808_newsdata_Korea_000001
 2      20230808_newsdata_Korea_000001
 3      20230808_newsdata_Korea_000001
 4      20230808_newsdata_Korea_000001
 ...                               ...
 32490   20230905_newsdata_Yeon_002695
 32491   20230905_newsdata_Yeon_002695
 32492   20230905_newsdata_Yeon_002695
 32493   20230905_newsdata_Yeon_002695
 32494   20230905_newsdata_Yeon_002695

                                                 Filename  \
 0      C:/Users/USER/Desktop/news data/20230808_data_...
 1      C:/Users/USER/Desktop/news data/20230808_data_...
 2      C:/Users/USER/Desktop/news data/20230808_data_...
 3      C:/Users/USER/Desktop/news data/20230808_data_...
 4      C:/Users/USER/Desktop/news data/20230808_data_...
 ...                                                  ...
 32490  C:/Users/USER/Desktop/기사 데이터_로컬환경/20230905_dat...
 32491  C:/Users/USER/Desktop/기사 데이터_로컬환경/20230905_dat...
 32492  C:/Users/USER/Desktop/기사 데이터_로컬환경/20230905_dat...
 32493  C:/Users/USER/Desktop/기사 데이터_로컬환경/20230905_dat...
 32494  C:/Users/USER/Desktop/기사 데이터_로컬환경/20230905_dat...

                                                    Title   Pub_Type Pub_Subj  \
 0      Kyuhyun Super Junior, Suho EXO, dan Lee Seok H...  Newspaper    Korea
 1      Kyuhyun Super Junior, Suho EXO, dan Lee Seok H...  Newspaper    Korea
 2      Kyuhyun Super Junior, Suho EXO, dan Lee Seok H...  Newspaper    Korea
 3      Kyuhyun Super Junior, Suho EXO, dan Lee Seok H...  Newspaper    Korea
 4      Kyuhyun Super Junior, Suho EXO, dan Lee Seok H...  Newspaper    Korea
 ...                                                  ...        ...      ...
 32490             Park Si Yeon Melahirkan Bayi Perempuan  Newspaper     Yeon
 32491             Park Si Yeon Melahirkan Bayi Perempuan  Newspaper     Yeon
 32492             Park Si Yeon Melahirkan Bayi Perempuan  Newspaper     Yeon
 32493             Park Si Yeon Melahirkan Bayi Perempuan  Newspaper     Yeon
 32494             Park Si Yeon Melahirkan Bayi Perempuan  Newspaper     Yeon

          Pub_Date    Col_Date                                    Sen_ID  \
 0      2019-10-30  2023-08-08  20230808_newsdata_Korea_000001_sen000001
 1      2019-10-30  2023-08-08  20230808_newsdata_Korea_000001_sen000002
 2      2019-10-30  2023-08-08  20230808_newsdata_Korea_000001_sen000003
 3      2019-10-30  2023-08-08  20230808_newsdata_Korea_000001_sen000004
 4      2019-10-30  2023-08-08  20230808_newsdata_Korea_000001_sen000005
 ...           ...         ...                                       ...
 32490  2013-09-24  2023-09-05   20230905_newsdata_Yeon_002695_sen000001
 32491  2013-09-24  2023-09-05   20230905_newsdata_Yeon_002695_sen000002
 32492  2013-09-24  2023-09-05   20230905_newsdata_Yeon_002695_sen000003
 32493  2013-09-24  2023-09-05   20230905_newsdata_Yeon_002695_sen000004
 32494  2013-09-24  2023-09-05   20230905_newsdata_Yeon_002695_sen000005

        Word_Count                                               Text  ...  \
 0              23   Kyuhyun Super Junior, Suho EXO, dan Lee Seok ...  ...
 1              15   Kyuhyun Super Junior, Suho EXO, dan Lee Seok ...  ...
 2              13   Kyuhyun Super Junior, Suho EXO, dan Lee Seok ...  ...
 3              33   Kyuhyun Super Junior, Suho EXO, dan Lee Seok ...  ...
 4              17   Kyuhyun Super Junior, Suho EXO, dan Lee Seok ...  ...
 ...           ...                                                ...  ...
 32490          23  Park Si Yeon telah melahirkan bayi perempuan, ...  ...
 32491          25  Park Si Yeon telah melahirkan bayi perempuan, ...  ...
 32492           7  Park Si Yeon telah melahirkan bayi perempuan, ...  ...
 32493          14  Park Si Yeon telah melahirkan bayi perempuan, ...  ...
 32494           6  Park Si Yeon telah melahirkan bayi perempuan, ...  ...

       Column_237 Column_238 Column_239 Column_240 Column_241 Column_242  \
 0            NaN        NaN        NaN        NaN        NaN        NaN
 1            NaN        NaN        NaN        NaN        NaN        NaN
 2            NaN        NaN        NaN        NaN        NaN        NaN
 3            NaN        NaN        NaN        NaN        NaN        NaN
 4            NaN        NaN        NaN        NaN        NaN        NaN
 ...          ...        ...        ...        ...        ...        ...
 32490        NaN        NaN        NaN        NaN        NaN        NaN
 32491        NaN        NaN        NaN        NaN        NaN        NaN
 32492        NaN        NaN        NaN        NaN        NaN        NaN
 32493        NaN        NaN        NaN        NaN        NaN        NaN
 32494        NaN        NaN        NaN        NaN        NaN        NaN

       Column_243 Column_244 Column_245 Column_246
 0            NaN        NaN        NaN        NaN
 1            NaN        NaN        NaN        NaN
 2            NaN        NaN        NaN        NaN
 3            NaN        NaN        NaN        NaN
 4            NaN        NaN        NaN        NaN
 ...          ...        ...        ...        ...
 32490        NaN        NaN        NaN        NaN
 32491        NaN        NaN        NaN        NaN
 32492        NaN        NaN        NaN        NaN
 32493        NaN        NaN        NaN        NaN
 32494        NaN        NaN        NaN        NaN

 [382495 rows x 260 columns])

In [3]:
xl_df

,Doc_ID,Filename,Title,Pub_Type,Pub_Subj,Pub_Date,Col_Date,Sen_ID,Word_Count,Text,...,Column_519,Column_520,Column_521,Column_522,Column_523,Column_524,Column_525,Column_526,Column_527,Column_528
0,20230809_newsdata_Korea_001327,C:/Users/USER/Desktop/news data/20230809_data/...,SNSD Siap Comeback di Bulan Januari dengan Kon...,Newspaper,Korea,2013-12-07,2023-08-09,20230809_newsdata_Korea_001327_sen000004,17,Girls' Generation akan comeback awal tahun dep...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20230809_newsdata_Korea_001327,C:/Users/USER/Desktop/news data/20230809_data/...,SNSD Siap Comeback di Bulan Januari dengan Kon...,Newspaper,Korea,2013-12-07,2023-08-09,20230809_newsdata_Korea_001327_sen000005,15,Girls' Generation akan comeback awal tahun dep...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20230809_newsdata_Korea_001327,C:/Users/USER/Desktop/news data/20230809_data/...,SNSD Siap Comeback di Bulan Januari dengan Kon...,Newspaper,Korea,2013-12-07,2023-08-09,20230809_newsdata_Korea_001327_sen000006,11,Girls' Generation akan comeback awal tahun dep...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20230809_newsdata_Korea_001327,C:/Users/USER/Desktop/news data/20230809_data/...,SNSD Siap Comeback di Bulan Januari dengan Kon...,Newspaper,Korea,2013-12-07,2023-08-09,20230809_newsdata_Korea_001327_sen000007,14,Girls' Generation akan comeback awal tahun dep...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20230809_newsdata_Korea_001327,C:/Users/USER/Desktop/news data/20230809_data/...,SNSD Siap Comeback di Bulan Januari dengan Kon...,Newspaper,Korea,2013-12-07,2023-08-09,20230809_newsdata_Korea_001327_sen000008,9,Girls' Generation akan comeback awal tahun dep...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44177,20231023_newsdata_Yoo Ah in_000249,C:/Users/USER/Desktop/기사 데이터_로컬환경/20231023_dat...,Park Ju Hyun Cerita Soal Film Barunya Bareng Y...,Newspaper,NaN,2021-11-08,2023-10-23,20231023_newsdata_Yoo Ah in_000249_sen000006,22,Dalam wawancara dan pemotretan baru-baru in...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44178,20231023_newsdata_Yoo Ah in_000249,C:/Users/USER/Desktop/기사 데이터_로컬환경/20231023_dat...,Park Ju Hyun Cerita Soal Film Barunya Bareng Y...,Newspaper,NaN,2021-11-08,2023-10-23,20231023_newsdata_Yoo Ah in_000249_sen000007,28,Dalam wawancara dan pemotretan baru-baru in...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44179,20231023_newsdata_Yoo Ah in_000249,C:/Users/USER/Desktop/기사 데이터_로컬환경/20231023_dat...,Park Ju Hyun Cerita Soal Film Barunya Bareng Y...,Newspaper,NaN,2021-11-08,2023-10-23,20231023_newsdata_Yoo Ah in_000249_sen000008,17,Dalam wawancara dan pemotretan baru-baru in...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44180,20231023_newsdata_Yoo Ah in_000249,C:/Users/USER/Desktop/기사 데이터_로컬환경/20231023_dat...,Park Ju Hyun Cerita Soal Film Barunya Bareng Y...,Newspaper,NaN,2021-11-08,2023-10-23,20231023_newsdata_Yoo Ah in_000249_sen000009,29,Dalam wawancara dan pemotretan baru-baru in...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44181,20231023_newsdata_Yoo Ah in_000249,C:/Users/USER/Desktop/기사 데이터_로컬환경/20231023_dat...,Park Ju Hyun Cerita Soal Film Barunya Bareng Y...,Newspaper,NaN,2021-11-08,2023-10-23,20231023_newsdata_Yoo Ah in_000249_sen000010,15,Dalam wawancara dan pemotretan baru-baru in...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# csv_df에서 ref에 있는 Doc_ID를 제거한다.
csv_df = csv_df[~csv_df["Doc_ID"].isin(ref)]
csv_df

,Doc_ID,Filename,Title,Pub_Type,Pub_Subj,Pub_Date,Col_Date,Sen_ID,Word_Count,Text,...,Column_237,Column_238,Column_239,Column_240,Column_241,Column_242,Column_243,Column_244,Column_245,Column_246
0,20230808_newsdata_Korea_000001,C:/Users/USER/Desktop/news data/20230808_data_...,"Kyuhyun Super Junior, Suho EXO, dan Lee Seok H...",Newspaper,Korea,2019-10-30,2023-08-08,20230808_newsdata_Korea_000001_sen000001,23,"Kyuhyun Super Junior, Suho EXO, dan Lee Seok ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20230808_newsdata_Korea_000001,C:/Users/USER/Desktop/news data/20230808_data_...,"Kyuhyun Super Junior, Suho EXO, dan Lee Seok H...",Newspaper,Korea,2019-10-30,2023-08-08,20230808_newsdata_Korea_000001_sen000002,15,"Kyuhyun Super Junior, Suho EXO, dan Lee Seok ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20230808_newsdata_Korea_000001,C:/Users/USER/Desktop/news data/20230808_data_...,"Kyuhyun Super Junior, Suho EXO, dan Lee Seok H...",Newspaper,Korea,2019-10-30,2023-08-08,20230808_newsdata_Korea_000001_sen000003,13,"Kyuhyun Super Junior, Suho EXO, dan Lee Seok ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20230808_newsdata_Korea_000001,C:/Users/USER/Desktop/news data/20230808_data_...,"Kyuhyun Super Junior, Suho EXO, dan Lee Seok H...",Newspaper,Korea,2019-10-30,2023-08-08,20230808_newsdata_Korea_000001_sen000004,33,"Kyuhyun Super Junior, Suho EXO, dan Lee Seok ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20230808_newsdata_Korea_000001,C:/Users/USER/Desktop/news data/20230808_data_...,"Kyuhyun Super Junior, Suho EXO, dan Lee Seok H...",Newspaper,Korea,2019-10-30,2023-08-08,20230808_newsdata_Korea_000001_sen000005,17,"Kyuhyun Super Junior, Suho EXO, dan Lee Seok ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31317,20230904_newsdata_Seok_001034,C:/Users/USER/Desktop/기사 데이터_로컬환경/20230904_dat...,Merawat Hutan Mangrove Kedatim: Ekosistem Puli...,Newspaper,Seok,2023-04-16,2023-09-04,20230904_newsdata_Seok_001034_sen000093,13,Namanya Wisata Mangrove Kebun Dadap Timur. ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31318,20230904_newsdata_Seok_001034,C:/Users/USER/Desktop/기사 데이터_로컬환경/20230904_dat...,Merawat Hutan Mangrove Kedatim: Ekosistem Puli...,Newspaper,Seok,2023-04-16,2023-09-04,20230904_newsdata_Seok_001034_sen000094,10,Namanya Wisata Mangrove Kebun Dadap Timur. ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31319,20230904_newsdata_Seok_001034,C:/Users/USER/Desktop/기사 데이터_로컬환경/20230904_dat...,Merawat Hutan Mangrove Kedatim: Ekosistem Puli...,Newspaper,Seok,2023-04-16,2023-09-04,20230904_newsdata_Seok_001034_sen000095,30,Namanya Wisata Mangrove Kebun Dadap Timur. ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31320,20230904_newsdata_Seok_001034,C:/Users/USER/Desktop/기사 데이터_로컬환경/20230904_dat...,Merawat Hutan Mangrove Kedatim: Ekosistem Puli...,Newspaper,Seok,2023-04-16,2023-09-04,20230904_newsdata_Seok_001034_sen000096,21,Namanya Wisata Mangrove Kebun Dadap Timur. ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31895,20230905_newsdata_Eun_003559,C:/Users/USER/Desktop/기사 데이터_로컬환경/20230905_dat...,Dal Shabet Rilis Foto Teaser untuk Album Mini ...,Newspaper,Eun,2015-12-28,2023-09-05,20230905_newsdata_Eun_003559_sen000001,16,Jelang perilisan album mini kesembilan 'Natu...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:

# xl_df에 csv_df를 추가한다.
xl_df = pandas.concat([xl_df, csv_df])

print_log("xl_df에 csv_df를 추가했습니다.")

xl_df

2023-12-04 14:54:21.189947	xl_df에 csv_df를 추가했습니다.

,Doc_ID,Filename,Title,Pub_Type,Pub_Subj,Pub_Date,Col_Date,Sen_ID,Word_Count,Text,...,Column_519,Column_520,Column_521,Column_522,Column_523,Column_524,Column_525,Column_526,Column_527,Column_528
0,20230809_newsdata_Korea_001327,C:/Users/USER/Desktop/news data/20230809_data/...,SNSD Siap Comeback di Bulan Januari dengan Kon...,Newspaper,Korea,2013-12-07 00:00:00,2023-08-09 00:00:00,20230809_newsdata_Korea_001327_sen000004,17,Girls' Generation akan comeback awal tahun dep...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20230809_newsdata_Korea_001327,C:/Users/USER/Desktop/news data/20230809_data/...,SNSD Siap Comeback di Bulan Januari dengan Kon...,Newspaper,Korea,2013-12-07 00:00:00,2023-08-09 00:00:00,20230809_newsdata_Korea_001327_sen000005,15,Girls' Generation akan comeback awal tahun dep...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20230809_newsdata_Korea_001327,C:/Users/USER/Desktop/news data/20230809_data/...,SNSD Siap Comeback di Bulan Januari dengan Kon...,Newspaper,Korea,2013-12-07 00:00:00,2023-08-09 00:00:00,20230809_newsdata_Korea_001327_sen000006,11,Girls' Generation akan comeback awal tahun dep...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20230809_newsdata_Korea_001327,C:/Users/USER/Desktop/news data/20230809_data/...,SNSD Siap Comeback di Bulan Januari dengan Kon...,Newspaper,Korea,2013-12-07 00:00:00,2023-08-09 00:00:00,20230809_newsdata_Korea_001327_sen000007,14,Girls' Generation akan comeback awal tahun dep...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20230809_newsdata_Korea_001327,C:/Users/USER/Desktop/news data/20230809_data/...,SNSD Siap Comeback di Bulan Januari dengan Kon...,Newspaper,Korea,2013-12-07 00:00:00,2023-08-09 00:00:00,20230809_newsdata_Korea_001327_sen000008,9,Girls' Generation akan comeback awal tahun dep...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31317,20230904_newsdata_Seok_001034,C:/Users/USER/Desktop/기사 데이터_로컬환경/20230904_dat...,Merawat Hutan Mangrove Kedatim: Ekosistem Puli...,Newspaper,Seok,2023-04-16,2023-09-04,20230904_newsdata_Seok_001034_sen000093,13,Namanya Wisata Mangrove Kebun Dadap Timur. ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31318,20230904_newsdata_Seok_001034,C:/Users/USER/Desktop/기사 데이터_로컬환경/20230904_dat...,Merawat Hutan Mangrove Kedatim: Ekosistem Puli...,Newspaper,Seok,2023-04-16,2023-09-04,20230904_newsdata_Seok_001034_sen000094,10,Namanya Wisata Mangrove Kebun Dadap Timur. ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31319,20230904_newsdata_Seok_001034,C:/Users/USER/Desktop/기사 데이터_로컬환경/20230904_dat...,Merawat Hutan Mangrove Kedatim: Ekosistem Puli...,Newspaper,Seok,2023-04-16,2023-09-04,20230904_newsdata_Seok_001034_sen000095,30,Namanya Wisata Mangrove Kebun Dadap Timur. ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31320,20230904_newsdata_Seok_001034,C:/Users/USER/Desktop/기사 데이터_로컬환경/20230904_dat...,Merawat Hutan Mangrove Kedatim: Ekosistem Puli...,Newspaper,Seok,2023-04-16,2023-09-04,20230904_newsdata_Seok_001034_sen000096,21,Namanya Wisata Mangrove Kebun Dadap Timur. ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31895,20230905_newsdata_Eun_003559,C:/Users/USER/Desktop/기사 데이터_로컬환경/20230905_dat...,Dal Shabet Rilis Foto Teaser untuk Album Mini ...,Newspaper,Eun,2015-12-28,2023-09-05,20230905_newsdata_Eun_003559_sen000001,16,Jelang perilisan album mini kesembilan 'Natu...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# group_ids = numpy.arange(len(xl_df)) // 50000
# grouped = xl_df.groupby(group_ids)

# for i, group in grouped:
#     file_name = f"20231204_원천데이터(기사+한국관련기사)_중복제거_{i}.xlsx"
#     file_path = result_path / file_name
#     group.to_excel(file_path, index=False)

#     print_log(f"saved : {file_name}")

In [7]:
result_path.mkdir(exist_ok=True)
# xl_df를 저장한다.
if len(xl_df) > 50000:
    
    split_dfs = numpy.array_split(xl_df, len(xl_df) // 50000)
    for i, split_df in enumerate(split_dfs):
        file_name = f"20231204_원천데이터(기사+한국관련기사)_중복제거_{i}.xlsx"
        split_df.to_excel(result_path / file_name, index=False)
        print_log(f"saved: {result_path / file_name}")
else:
    xl_df.to_excel(result_path / f"20231204_원천데이터(기사+한국관련기사)_중복제거.xlsx")

C:\Users\정진혁\AppData\Roaming\Python\Python311\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)

2023-12-04 15:04:39.764463	saved: C:\Users\정진혁\offline_main\projectXpython\result_storage\catch_duplication\20231204_원천데이터(기사+한국관련기사)_중복제거_0.xlsx
2023-12-04 15:14:53.744097	saved: C:\Users\정진혁\offline_main\projectXpython\result_storage\catch_duplication\20231204_원천데이터(기사+한국관련기사)_중복제거_1.xlsx
2023-12-04 15:23:45.207421	saved: C:\Users\정진혁\offline_main\projectXpython\result_storage\catch_duplication\20231204_원천데이터(기사+한국관련기사)_중복제거_2.xlsx
2023-12-04 15:32:45.518701	saved: C:\Users\정진혁\offline_main\projectXpython\result_storage\catch_duplication\20231204_원천데이터(기사+한국관련기사)_중복제거_3.xlsx
2023-12-04 15:41:45.289174	saved: C:\Users\정진혁\offline_main\projectXpython\result_storage\catch_duplication\20231204_원천데이터(기사+한국관련기사)_중복제거_4.xlsx
2023-12-04 15:50:43.490013	saved: C:\Users\정진혁\offline_main\projectXpython\result_storage\catch_duplication\20231204_원천데이터(기사+한국관련기사)_중복제거_5.xlsx
2023-12-04 15:59:42.119206	saved: C:\Users\정진혁\offline_main\projectXpython\result_storage\catch_duplication\20231204_원천데이터(기사+한국관련기사)_중복제거_6.xlsx
2023-12-04 16:10:40.417912	saved: C:\Users\정진혁\offline_main\projectXpython\result_storage\catch_duplication\20231204_원천데이터(기사+한국관련기사)_중복제거_7.xlsx
2023-12-04 16:23:19.723541	saved: C:\Users\정진혁\offline_main\projectXpython\result_storage\catch_duplication\20231204_원천데이터(기사+한국관련기사)_중복제거_8.xlsx
2023-12-04 16:34:26.943763	saved: C:\Users\정진혁\offline_main\projectXpython\result_storage\catch_duplication\20231204_원천데이터(기사+한국관련기사)_중복제거_9.xlsx
2023-12-04 16:43:36.886268	saved: C:\Users\정진혁\offline_main\projectXpython\result_storage\catch_duplication\20231204_원천데이터(기사+한국관련기사)_중복제거_10.xlsx
2023-12-04 16:53:48.419096	saved: C:\Users\정진혁\offline_main\projectXpython\result_storage\catch_duplication\20231204_원천데이터(기사+한국관련기사)_중복제거_11.xlsx